id: P9A9BFA68
initial_creation_type: input
source_metadata:
  Title: Pañcaskandhaprakaraṇam
  Editor: Shastri, Shantibhiksu
  Publisher: Journal of Sampurnanda Sanskrit University
  Place of Publication: India
  Year: '1955'
  Pañcaskandhaprakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:56:13.833440'
last_modified_at: '2022-03-08T16:56:13.833448'
